name: 'k8s Deployment'
description: >
  jsut some testing
inputs:
  environment:
    description: 'Hard requirement on which environment to use'
    required: false
  image:
    description: "Image name. Defaults to repository name"
    required: false
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.testscript.outputs.testscript }}
runs:
  using: 'composite'
  steps:
    - id: testscript
      run: echo "::set-output name=testscript::$(${{GITHUB_ACTION_REPOSITORY}}/test.sh)"
      shell: bash
